dependencies: 
  # - <organization/repo>@<version)
    - aave/protocol-v2@1.0.1
compiler: 
  solc:
    remappings:
      - '@aave=aave/protocol-v2@1.0.1'
      

dotenv: .env
networks:
  default: mainnet-fork
  deveopment:
  kovan:
    fee: 100000000000000000
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c'
    address_provider: '0x88757f2f99175387aB4C6a4b3067c77A695b0349'
    verify: True
  mainnet-fork:
    weth_token: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'
    address_provider: '0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5'
    verify: False
  ganache-local:
      verify: False
  rinkeby:
  mainnet:

  

wallets:
  from_key: ${PRIVATE_KEY}
